// Skill router for the assistant chat intelligence model v2.
// Loads all 70 skill .md files at module init, parses YAML frontmatter,
// builds a trigger-keyword index, and exposes matchSkill() for prompt assembly.

interface SkillFrontmatter {
  name: string;
  pillars?: string[];
  surface?: string;
  trigger?: string[];
}

export interface Skill {
  slug: string;
  name: string;
  pillars: string[];
  surface: string;
  triggers: string[];
  body: string; // full markdown after frontmatter
  raw: string; // entire file
}

// --- Frontmatter parser (minimal YAML for our schema) ---
function parseFrontmatter(raw: string): { fm: SkillFrontmatter; body: string } {
  if (!raw.startsWith("---")) return { fm: { name: "" }, body: raw };
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return { fm: { name: "" }, body: raw };
  const fmText = raw.slice(3, end).trim();
  const body = raw.slice(end + 4).replace(/^\s*\n/, "");
  const fm: any = {};
  for (const line of fmText.split("\n")) {
    const m = line.match(/^([a-zA-Z_]+)\s*:\s*(.*)$/);
    if (!m) continue;
    const key = m[1].trim();
    const val = m[2].trim();
    if (key === "pillars" || key === "trigger") {
      fm[key] = val.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
    } else {
      fm[key] = val;
    }
  }
  return { fm: fm as SkillFrontmatter, body };
}

// --- Load every skill at module init ---
// IMPORTANT: Supabase Edge Functions only bundle .ts/.js files referenced by
// imports. Reading .md files via Deno.readTextFileSync at runtime fails in
// production (the .md files aren't shipped). So we precompile every skill
// into a string-keyed map in `_skills_bundle.ts` (regenerated by
// /tmp/build_skills.mjs whenever skills change) and load from there.
import { SKILL_BUNDLE } from "./_skills_bundle.ts";

const skills: Skill[] = [];

for (const [slug, raw] of Object.entries(SKILL_BUNDLE)) {
  try {
    const { fm, body } = parseFrontmatter(raw);
    skills.push({
      slug,
      name: fm.name || slug,
      pillars: fm.pillars || [],
      surface: fm.surface || "assistant-chat",
      triggers: (fm.trigger as any) || [],
      body,
      raw,
    });
  } catch (e) {
    console.warn(`[skill-router] failed to parse ${slug}:`, (e as Error).message);
  }
}

console.log(`[skill-router] loaded ${skills.length} skills from bundle`);

// --- Matching ---
export function matchSkill(message: string): Skill | null {
  if (!message) return null;
  const lower = message.toLowerCase();
  let best: { skill: Skill; score: number } | null = null;
  for (const skill of skills) {
    for (const trigger of skill.triggers) {
      if (!trigger) continue;
      if (lower.includes(trigger)) {
        const score = trigger.length; // longer phrase = more specific
        if (!best || score > best.score) best = { skill, score };
      }
    }
  }
  return best?.skill ?? null;
}

export function getSkill(slug: string): Skill | null {
  return skills.find((s) => s.slug === slug) ?? null;
}

export function listSkills(): Skill[] {
  return skills;
}

// Build the inject block for the system prompt.
export function buildSkillBlock(skill: Skill): string {
  return `\n\n## Active Skill: ${skill.name}\n*Pillars: ${skill.pillars.join(", ") || "none declared"}*\n\n${skill.body.trim()}\n`;
}
