// Skill router for the assistant chat intelligence model v2.
// Loads all 70 skill .md files at module init, parses YAML frontmatter,
// builds a trigger-keyword index, and exposes matchSkill() for prompt assembly.

interface SkillFrontmatter {
  name: string;
  pillars?: string[];
  surface?: string;
  trigger?: string[];
}

export interface Skill {
  slug: string;
  name: string;
  pillars: string[];
  surface: string;
  triggers: string[];
  body: string; // full markdown after frontmatter
  raw: string; // entire file
}

// --- Frontmatter parser (minimal YAML for our schema) ---
function parseFrontmatter(raw: string): { fm: SkillFrontmatter; body: string } {
  if (!raw.startsWith("---")) return { fm: { name: "" }, body: raw };
  const end = raw.indexOf("\n---", 3);
  if (end === -1) return { fm: { name: "" }, body: raw };
  const fmText = raw.slice(3, end).trim();
  const body = raw.slice(end + 4).replace(/^\s*\n/, "");
  const fm: any = {};
  for (const line of fmText.split("\n")) {
    const m = line.match(/^([a-zA-Z_]+)\s*:\s*(.*)$/);
    if (!m) continue;
    const key = m[1].trim();
    const val = m[2].trim();
    if (key === "pillars" || key === "trigger") {
      fm[key] = val.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
    } else {
      fm[key] = val;
    }
  }
  return { fm: fm as SkillFrontmatter, body };
}

// --- Load every skill at module init ---
// IMPORTANT: Supabase Edge Functions only bundle .ts/.js files referenced by
// imports. Reading .md files via Deno.readTextFileSync at runtime fails in
// production (the .md files aren't shipped). So we precompile every skill
// into a string-keyed map in `_skills_bundle.ts` (regenerated by
// /tmp/build_skills.mjs whenever skills change) and load from there.
import { SKILL_BUNDLE } from "./_skills_bundle.ts";

let skillsCache: Skill[] | null = null;

/** JIT: parse the precompiled bundle on first matcher use (faster cold start than eager init). */
function getAllSkills(): Skill[] {
  if (skillsCache) return skillsCache;
  const skills: Skill[] = [];
  for (const [slug, raw] of Object.entries(SKILL_BUNDLE)) {
    try {
      const { fm, body } = parseFrontmatter(raw);
      skills.push({
        slug,
        name: fm.name || slug,
        pillars: fm.pillars || [],
        surface: fm.surface || "assistant-chat",
        triggers: (fm.trigger as any) || [],
        body,
        raw,
      });
    } catch (e) {
      console.warn(`[skill-router] failed to parse ${slug}:`, (e as Error).message);
    }
  }
  skillsCache = skills;
  console.log(`[skill-router] loaded ${skills.length} skills from bundle (lazy)`);
  return skills;
}

// --- Matching ---
export function matchSkill(message: string): Skill | null {
  if (!message) return null;
  const lower = message.toLowerCase();
  let best: { skill: Skill; score: number } | null = null;
  for (const skill of getAllSkills()) {
    for (const trigger of skill.triggers) {
      if (!trigger) continue;
      if (lower.includes(trigger)) {
        const score = trigger.length; // longer phrase = more specific
        if (!best || score > best.score) best = { skill, score };
      }
    }
  }
  return best?.skill ?? null;
}

/**
 * Sticky skill matcher for multi-turn flows like Agent / Employee creation
 * wizards. The user's first message ("create an agent") matches the skill,
 * but subsequent replies (e.g. clicking a SUGGEST chip like "📥 Lead triage")
 * carry no trigger keywords — without stickiness the assistant drops the
 * skill and answers the chip text as a free-form question.
 *
 * Strategy:
 *   1. Match against the latest user message (existing behaviour).
 *   2. If no direct match, scan up to the last 8 user messages and pick the
 *      most recent one that matches a skill. This keeps wizards alive across
 *      short answers without permanently locking the assistant into a skill.
 *
 * `messages` may be the raw chat history with role + content (string or
 * array of multimodal parts).
 */
export function matchSkillSticky(messages: any[]): Skill | null {
  if (!messages || messages.length === 0) return null;
  const userMsgs: string[] = [];
  for (let i = messages.length - 1; i >= 0 && userMsgs.length < 8; i--) {
    const m = messages[i];
    if (!m || m.role !== "user") continue;
    const c = m.content;
    let text = "";
    if (typeof c === "string") text = c;
    else if (Array.isArray(c)) text = c.filter((p: any) => p?.type === "text").map((p: any) => p.text).join(" ");
    if (text) userMsgs.push(text);
  }
  for (const text of userMsgs) {
    const hit = matchSkill(text);
    if (hit) return hit;
  }
  return null;
}

/** Match up to N skills by trigger overlap (longer trigger wins). */
export function matchSkillsForMessage(message: string, maxSkills = 3): Skill[] {
  if (!message) return [];
  const lower = message.toLowerCase();
  const scored: { skill: Skill; score: number }[] = [];
  for (const skill of skills) {
    let best = 0;
    for (const trigger of skill.triggers) {
      if (!trigger) continue;
      if (lower.includes(trigger)) best = Math.max(best, trigger.length);
    }
    if (best > 0) scored.push({ skill, score: best });
  }
  scored.sort((a, b) => b.score - a.score);
  const out: Skill[] = [];
  const seen = new Set<string>();
  for (const { skill } of scored) {
    if (out.length >= maxSkills) break;
    if (seen.has(skill.slug)) continue;
    seen.add(skill.slug);
    out.push(skill);
  }
  return out;
}

export function buildSkillsBlock(matched: Skill[]): string {
  if (matched.length === 0) return "";
  const header =
    "## Skill playbooks matched this turn\n" +
    "These are **methodology and framing** — not a source of private business facts. " +
    "Still ground every factual claim about this workspace in Business DNA, live connector results, dashboard/KPIs, web snapshot, or user messages.\n" +
    "When a playbook implies **web research, crawling, or connector lookups**, use the **already-injected** blocks above (Connected Sources / External web research / dashboards) in this same reply. " +
    "Synthesize from what is present; if those sections are empty or say retrieval failed, say so plainly — do not answer as if research ran when it did not.\n" +
    "For **vague growth / strategy** asks, deliver a concrete plan first; do **not** chain many `[SUGGEST:…]` discovery rounds — at most one optional clarifier if a single fact would change the plan materially.\n\n";
  return header + matched.map(buildSkillBlock).join("\n");
}

export function getSkill(slug: string): Skill | null {
  return getAllSkills().find((s) => s.slug === slug) ?? null;
}

export function listSkills(): Skill[] {
  return getAllSkills();
}

// Build the inject block for the system prompt.
export function buildSkillBlock(skill: Skill): string {
  return `\n\n## Active Skill: ${skill.name}\n*Pillars: ${skill.pillars.join(", ") || "none declared"}*\n\n${skill.body.trim()}\n`;
}
