export default function TermsOfPurchase() {
  return (
    <div className="min-h-[1300px] bg-background text-foreground">
      <div className="max-w-[1900px] mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-3xl font-bold mb-8">Terms &amp; Information</h1>

        <div className="prose prose-invert max-w-none space-y-6 text-muted-foreground text-[15px] leading-relaxed">
          <div className="space-y-1 mb-8 text-sm">
            <p><strong className="text-foreground">Effective Date:</strong> March 29, 2026</p>
            <p><strong className="text-foreground">Company:</strong> Vincent Ackermann ("TimeWarpDev", "we", "our", "us")</p>
            <p><strong className="text-foreground">Organization Number:</strong> 081003XXXX</p>
            <p><strong className="text-foreground">Registered Address:</strong> Lillvägen 4, 182 49 Stockholm, Sweden</p>
            <p><strong className="text-foreground">Contact Email:</strong> <a href="mailto:vincentackermann@timewarpdev.com" className="text-primary underline">vincentackermann@timewarpdev.com</a></p>
          </div>

          <p>For clarity, the customer will be referred to as "you", TimeWarpDev as "we", and <a href="https://www.timewarpdev.com" className="text-primary underline">www.timewarpdev.com</a> as "the website".</p>
          <p>These Terms are written for your protection. By completing a purchase or using the website, you agree to these Terms. TimeWarpDev complies with the Swedish Distance and Off-Premises Contracts Act (2005:59).</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">1. Definitions</h2>
          <p>For purposes of these Terms:</p>
          <p><strong className="text-foreground">"Service"</strong> means the TimeWarpDev platform, web and mobile applications, APIs, tools, analytics, and any associated documentation or content provided by us.</p>
          <p><strong className="text-foreground">"User" or "Customer"</strong> means any individual or entity that registers for, accesses, or uses the Service.</p>
          <p><strong className="text-foreground">"Content"</strong> means any data, text, images, video, audio, or other material uploaded, submitted, transmitted, or otherwise made available by the User.</p>
          <p><strong className="text-foreground">"AI Output"</strong> means any material generated by TimeWarpDev's AI systems in response to User input.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">2. Acceptance of Terms</h2>
          <p>By accessing or using the Service, you:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Agree to be legally bound by these Terms and our Privacy Policy.</li>
            <li>Represent and warrant that you have the legal authority to enter into this agreement for yourself or your organization.</li>
          </ul>
          <p>If you do not agree to the Terms, you must not use the Service. Continued use after an update constitutes acceptance of the revised Terms.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">3. Account Registration and Security</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You must provide accurate, current, and complete information during registration and keep it updated.</li>
            <li>You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.</li>
            <li>We may suspend or terminate accounts in cases of breach, fraud, or security concerns.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">4. Prices</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>All prices on the website are displayed in USD ($).</li>
            <li>Prices exclude applicable taxes. VAT will be applied when required by law.</li>
            <li>EU customers with a valid VAT ID may qualify for reverse charge.</li>
            <li>Charges are made in the currency displayed at checkout.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">5. Payment</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Available payment methods are shown at checkout.</li>
            <li>If you are under 18 years old, an adult's approval is required before purchasing.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">6. Refund Policy</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>New customers may request a refund within 30 days of their first purchase, subject to Section 20.</li>
            <li>Refunds are not issued for renewals, downgrades, or unused portions of a subscription term.</li>
            <li>Cancellations take effect at the end of the current billing cycle.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">7. License and Permitted Use</h2>
          <p>We grant you a limited, non-exclusive, non-transferable, revocable license to use the Service for lawful purposes and in accordance with these Terms.</p>
          <p>You may not:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Reverse-engineer, decompile, or attempt to extract source code.</li>
            <li>Resell, sublicense, or provide third parties with access to the Service.</li>
            <li>Use the Service to create unlawful, discriminatory, defamatory, or infringing content.</li>
            <li>Circumvent technical limits or integrate with unapproved systems.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">8. Google User Data</h2>
          <p>If you connect your Google account, TimeWarpDev may access certain Google user data via Google OAuth strictly to provide features you request.</p>

          <h3 className="text-lg font-semibold text-foreground mt-6">Access &amp; Use</h3>
          <ul className="list-disc pl-6 space-y-1">
            <li>We access only the Google data explicitly authorized by you through Google's consent screen.</li>
            <li>We do not use Google data for advertising, profiling, or unrelated purposes.</li>
          </ul>

          <h3 className="text-lg font-semibold text-foreground mt-6">Storage &amp; Security</h3>
          <p>Google user data is stored only as long as necessary for functionality and protected with industry-standard security measures.</p>

          <h3 className="text-lg font-semibold text-foreground mt-6">Sharing &amp; Disclosure</h3>
          <p>We do not sell, rent, or share Google user data with third parties, except when needed to operate the requested functionality or when required by law.</p>

          <h3 className="text-lg font-semibold text-foreground mt-6">User Control &amp; Revocation</h3>
          <ul className="list-disc pl-6 space-y-1">
            <li>You may revoke access at any time via your Google Account settings.</li>
            <li>When access is revoked, we cease access and delete stored Google data unless retention is legally required.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">9. Service Availability</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>We target 99.9% monthly uptime, but uninterrupted service is not guaranteed.</li>
            <li>Downtime may occur due to maintenance, updates, or third-party outages.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">10. Termination</h2>
          <p>We may suspend or terminate your account, with or without notice, if you:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Breach these Terms.</li>
            <li>Engage in fraud, abuse, or unlawful activity.</li>
            <li>Are legally required to cease use.</li>
          </ul>
          <p>Upon termination, your license to use the Service ends immediately.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">11. Indemnification</h2>
          <p>You agree to indemnify and hold harmless TimeWarpDev, its officers, directors, employees, and affiliates from any claims, damages, or costs arising out of:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Your use of the Service.</li>
            <li>Your Content or AI Output.</li>
            <li>Your violation of laws or third-party rights.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">12. Disclaimers</h2>
          <p>The Service is provided "as is" without warranties of any kind, express or implied.</p>
          <p>We do not guarantee that:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>The Service will be error-free or uninterrupted.</li>
            <li>AI Output will be accurate or suitable for a specific purpose.</li>
            <li>Third-party content or integrations will be reliable.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">13. Force Majeure</h2>
          <p>TimeWarpDev is not responsible for delays or failures caused by circumstances outside our reasonable control, including: war, strikes, natural disasters, labor conflicts, government actions, supplier failures, or other unforeseeable events that affect performance.</p>

          <h2 className="text-xl font-semibold text-foreground mt-8">14. Governing Law &amp; Jurisdiction</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>These Terms are governed by Swedish law.</li>
            <li>The courts of Stockholm, Sweden, have exclusive jurisdiction over disputes arising from these Terms or the Service.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">15. Changes to Terms</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>We may revise these Terms at any time. Updated versions will be posted on the website.</li>
            <li>Material changes may also be communicated via email or in-Service notifications.</li>
            <li>Continued use of the Service after updates constitutes acceptance.</li>
          </ul>

          <h2 className="text-xl font-semibold text-foreground mt-8">Contact</h2>
          <p><strong className="text-foreground">Vincent Ackermann</strong></p>
          <p>Email: <a href="mailto:vincentackermann@timewarpdev.com" className="text-primary underline">vincentackermann@timewarpdev.com</a></p>
          <p>Address: Lillvägen 4, 182 49 Stockholm, Sweden</p>
        </div>
      </div>
    </div>
  );
}